Repository davidgonmar/uvlhub-egc, pull requests merged in 2024-11, with the labels that each got.

#104 feat(explore): Implement new filters. Closes #98
  app/modules/dataset/seeders.py
  app/modules/dataset/uvl_examples/file13.uvl
  app/modules/dataset/uvl_examples/file14.uvl
  app/modules/dataset/uvl_examples/file15.uvl
  app/modules/dataset/uvl_examples/file16.uvl
  app/modules/dataset/uvl_examples/file17.uvl
  app/modules/dataset/uvl_examples/file18.uvl
  app/modules/dataset/uvl_examples/file19.uvl
  app/modules/dataset/uvl_examples/file20.uvl
  app/modules/dataset/uvl_examples/file21.uvl
  app/modules/dataset/uvl_examples/file22.uvl
  app/modules/dataset/uvl_examples/file23.uvl
  app/modules/dataset/uvl_examples/file24.uvl
  app/modules/explore/assets/scripts.js
  app/modules/explore/repositories.py
  app/modules/explore/routes.py
  app/modules/explore/services.py
  app/modules/explore/templates/explore/index.html
Labels: backend, frontend, feat, task

#125 Fix incorrect behavior of "Explore" page
  app/modules/explore/repositories.py
Labels: backend, fix, incidence

#126 Transformation of uploaded UVL files into the rest of the platform's supported formats
  app/modules/dataset/routes.py
  app/modules/dataset/templates/dataset/upload_dataset.html
  app/modules/dataset/transformation_aux.py
Labels: backend, frontend, feat
