Repository davidgonmar/uvlhub-egc, pull requests merged in 2024-12, with the labels that each got.

#135 Rate models backend
  app/modules/featuremodel/models.py
  app/modules/featuremodel/repositories.py
  app/modules/featuremodel/services.py
  migrations/versions/5a20679d5b3f_.py
  migrations/versions/6706d9a1ec66_.py
Labels: backend, feat, task

#132 Chatbot Testing
  app/modules/chatbot/routes.py
  app/modules/chatbot/services.py
  app/modules/chatbot/tests/test_selenium_ide/test_chatbot_not_supported_language.py
  app/modules/chatbot/tests/test_selenium_ide/test_chatbot_out_of_context.py
  app/modules/chatbot/tests/test_selenium_ide/test_chatbot_succesful.py
  app/modules/chatbot/tests/test_unit.py
  requirements.txt
Labels: test

#169 Advanced Search UI Tests
  app/modules/dataset/tests/test_selenium_ide/test_clear_filters_button_UI.py
  app/modules/dataset/tests/test_selenium_ide/test_date_filter_UI.py
  app/modules/dataset/tests/test_selenium_ide/test_maxmin_size_filter_UI.py
  app/modules/dataset/tests/test_selenium_ide/test_maxmin_uvl_filter_UI.py
  app/modules/dataset/tests/test_selenium_ide/test_publication_type_filter_UI.py
Labels: test, Review effort [1-5]: 2

#164 Unit and locust test for advanced search
  app/modules/explore/tests/locustfile.py
  app/modules/explore/tests/test_unit.py
  app/modules/fakenodo/tests/__init__.py
  app/modules/notepad/tests/locustfile.py
  migrations/versions/22295a2a5d13_.py
Labels: test

#174 Fix Publication DOI
  app/modules/dataset/assets/scripts.js
  app/modules/dataset/forms.py
  app/modules/dataset/routes.py
  app/modules/fakenodo/services.py
Labels: Review effort [1-5]: 3

#163 Tests search queries capability
  app/modules/explore/tests/locustfile.py
  app/modules/explore/tests/test_selenium.py
  app/modules/explore/tests/test_selenium_2.py
  app/modules/explore/tests/test_unit.py
Labels: backend, frontend, test

#181 Remove environment from actions
  .github/workflows/codacy.yml
  .github/workflows/tests.yml
Labels: Review effort [1-5]: 1

#171 Add locust test for Fakenodo
  app/modules/fakenodo/tests/locustfile.py
Labels: test, Review effort [1-5]: 2

#193 Merge main into build
  .github/workflows/PR_agent.yml
  app/modules/chatbot/tests/test_selenium_ide/test_chatbot_not_supported_language.py
  app/modules/chatbot/tests/test_selenium_ide/test_chatbot_out_of_context.py
  app/modules/chatbot/tests/test_selenium_ide/test_chatbot_succesful.py
  app/modules/dataset/tests/test_selenium_ide/test_maxmin_uvl_filter_UI.py
  app/modules/dataset/tests/test_selenium_ide/test_publication_type_filter_UI.py
  app/modules/explore/tests/test_selenium_ide/test_clear_filters_button_UI.py
  app/modules/explore/tests/test_selenium_ide/test_date_filter_UI.py
  app/modules/explore/tests/test_selenium_ide/test_maxmin_size_filter_UI.py
  app/modules/explore/tests/test_selenium_ide/test_maxmin_uvl_filter_UI.py
  app/modules/explore/tests/test_selenium_ide/test_publication_type_filter_UI.py
  app/modules/fakenodo/tests/locustfile.py
Labels: Review effort [1-5]: 2

#186 Remove breaking and unnecesary migration
  migrations/versions/22295a2a5d13_.py
Labels: incidence, Review effort [1-5]: 1

#194 Use webhook instead of auto-deploy for Render deployment
  .github/workflows/deloyment_on_webhook.yml
  .github/workflows/deployment_on_render.yml
Labels: Review effort [1-5]: 1

#191 Add Repository Pipeline Documentation
  documentation/g1/Pipeline_del_Repositorio.md
Labels: Review effort [1-5]: 1

#198 Fix desincronization of ids when login with Orcid
  app/modules/auth/routes.py
Labels: fix

#199 CI Monthly Contribution Report WF
  .github/workflows/monthly_report.yml
Labels: feat

#200 Fix Monthly Contribution Report
  .github/workflows/historical_report.yml
  .github/workflows/monthly_report.yml
Labels: feat

#182 Tests for 'Rate Models/Datasets'
  app/modules/dataset/routes.py
  app/modules/dataset/tests/test_selenium_ide/test_ratedataset.py
  app/modules/dataset/tests/test_unit.py
  app/modules/featuremodel/routes.py
  app/modules/featuremodel/tests/test_selenium_ide/test_ratefeaturemodel.py
  app/modules/featuremodel/tests/test_unit.py
Labels: test, Review effort [1-5]: 2

#208 Move Selenium tests to a dedicated subdirectory
  app/modules/explore/tests/test_selenium.py
  app/modules/explore/tests/test_selenium_2.py
Labels: test, incidence, Review effort [1-5]: 1

#209 Add migration workflow
  .github/workflows/validate_migrations.yml
  scripts/validate_migrations.py
Labels: build, Review effort [1-5]: 3

#210 Re-add and rename Selenium test files to the corresponding folder
  app/modules/explore/tests/test_selenium_ide/test_search_queries_2.py
  app/modules/explore/tests/test_selenium_ide/test_search_query.py
Labels: backend, refactor, test, Review effort [1-5]: 2

#212 Re-generate migrations
  migrations/versions/053b73151a92_.py
  migrations/versions/1fddf9da2e5e_.py
  migrations/versions/22cc32aab8bf_.py
  migrations/versions/5a20679d5b3f_.py
  migrations/versions/6706d9a1ec66_.py
  migrations/versions/8e427fc7cd5f_.py
  migrations/versions/99e9242e6a9b_.py
  migrations/versions/a77dce7b3e36_.py
  migrations/versions/ebc8f43d4986_.py
  migrations/versions/f102ec75299f_.py
  migrations/versions/f74959573e76_.py
Labels: incidence, Review effort [1-5]: 3

#220 Only deploy on changes to main
  .github/workflows/deployment_on_render.yml
Labels: build, incidence, Review effort [1-5]: 1

#222 Add seed.yml
  .github/workflows/seed.yml
Labels: Review effort [1-5]: 1

#223 Make seed workflow work
  .github/workflows/seed.yml
  docker/images/Dockerfile.render
Labels: Review effort [1-5]: 1

#224 Copy also setup.py in Dockerfile.render
  docker/images/Dockerfile.render
Labels: build, Review effort [1-5]: 1

#207 Tests for Multiple Login
  app/modules/auth/tests/test_unit.py
Labels: test, Review effort [1-5]: 3

#232 Make seeder finally work
  .github/workflows/seed.yml
  docker/images/Dockerfile.render
Labels: build, Review effort [1-5]: 2

#226 Adapt test to new changes added
  app/modules/auth/tests/test_selenium_ide/test_developercheckbox.py
  app/modules/auth/tests/test_selenium_ide/test_developergithub.py
  app/modules/dataset/tests/test_selenium.py
  app/modules/dataset/tests/test_selenium_ide/Test_UI.py
Labels: Review effort [1-5]: 2

#231 Update env files with placeholders.
  .env.docker.example
  .env.docker.production.example
  .env.local.example
  .env.vagrant.example
Labels: Review effort [1-5]: 1

#230 Update readme descriptions and add dockerhub section
  .github/workflows/deployment_on_dockerhub.yml
  README.md
Labels: Review effort [1-5]: 2

#228 CI dockerhub image
  .github/workflows/deployment_on_dockerhub.yml
Labels: Review effort [1-5]: 2

#187 Frontend for staging area.
  app/modules/dataset/routes.py
  app/modules/dataset/seeders.py
  app/modules/dataset/templates/dataset/staging_area_dataset.html
  app/modules/explore/routes.py
  app/modules/explore/tests/test_unit.py
  app/modules/public/routes.py
  app/modules/public/templates/public/index.html
Labels: Review effort [1-5]: 4

#233 Fix selenium test errors
  app/modules/dataset/tests/test_selenium_ide/test_DifferentModels.py
  app/modules/dataset/tests/test_selenium_ide/test_UI.py
Labels: Review effort [1-5]: 2

#234 G2/incidence 4/add checkmark to developer datasets in explore
  app/modules/dataset/models.py
  app/modules/explore/assets/scripts.js
Labels: Review effort [1-5]: 2

#237 Add new PR label workflow
  .github/workflows/pr_label.yml
Labels: task, Review effort [1-5]: 2

#205 Final update of G1 documentation
  documentation/g1/Acta_fundacional-G1.md
  documentation/g1/Diario_del_equipo-G1.md
  documentation/g1/Documento_del_proyecto-G1.md
  documentation/g1/Pipeline_del_Repositorio-G1.md
  documentation/g1/Pipeline_del_Repositorio.md
Labels: Review effort [1-5]: 1

#238 Clean the code in explore and auth modules.
  app/modules/auth/services.py
  app/modules/explore/repositories.py
Labels: Review effort [1-5]: 2

#239 Real final documentation changes of G1
  documentation/g1/Documento_del_proyecto-G1.md
Labels: Review effort [1-5]: 1

#206 Final documentation changes for G2.
  documentation/g2/Acta_fundacional-G2.md
  documentation/g2/Diario_del_equipo-G2.md
  documentation/g2/Documento_del_proyecto-G2.md
  documentation/g2/Pipeline_del_Repositorio.md
Labels: Review effort [1-5]: 2

#242 Fix seeders workflow
  .github/workflows/seed.yml
Labels: database, build, Review effort [1-5]: 2

#244 Resolve the deletion issue with duplicate UVL file names
  app/modules/dataset/templates/dataset/upload_dataset.html
Labels: backend, fix, incidence, Review effort [1-5]: 2

#246 Fix incorrect count of models
  app/modules/featuremodel/repositories.py
Labels: fix, incidence, Review effort [1-5]: 2

#247 True final update of 'Documento del proyecto' of G1
  documentation/g1/Documento_del_proyecto-G1.md
Labels: Review effort [1-5]: 1

#250 Fix selenium tests
  app/modules/auth/tests/test_selenium.py
  app/modules/chatbot/tests/test_selenium_ide/test_chatbot_not_supported_language.py
  app/modules/chatbot/tests/test_selenium_ide/test_chatbot_out_of_context.py
  app/modules/featuremodel/tests/test_selenium_ide/test_ratefeaturemodel.py
Labels: Review effort [1-5]: 2

#251 Last update to README file
  README.md
Labels: Review effort [1-5]: 1

#255 M3 Cambiar Nombre del Chatbot
  app/modules/chatbot/templates/chatbot/index.html
Labels: feat, Review effort [1-5]: 1
